# -*- coding: utf-8 -*-
"""September 28 Lab Activity Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqZtSNqnzDVagGp89nnT67VTw5tPQkWh
"""

# ============================================================
# SETUP
# ============================================================

!pip install scipy pandas matplotlib

import urllib.request
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde
from io import StringIO


# ============================================================
# DOWNLOAD AND LOAD NCBI REFSEQ DATA
# ============================================================

urllib.request.urlretrieve(
    "https://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/assembly_summary_refseq.txt",
    "assembly_summary_refseq.txt"
)

# Read file
with open("assembly_summary_refseq.txt", "r") as file:
    g_data = file.read()

# Remove # symbols
cleaned_lines = [line.replace("#", "") for line in g_data]

# Convert to dataframe
data_string = "".join(cleaned_lines)

g_data = pd.read_csv(
    StringIO(data_string),
    sep="\t",
    skiprows=1,
    quoting=3,
    engine="python"
)


# ============================================================
# FIGURE 1: PINK GC CONTENT HISTOGRAM — 20–80%
# ============================================================

# Make GC percent numeric
g_data["gc_percent"] = pd.to_numeric(
    g_data["gc_percent"],
    errors="coerce"
)

plt.figure(figsize=(10, 6))

plt.hist(
    g_data["gc_percent"].dropna(),
    bins=30,
    color="pink"
)

plt.title("GC Content Histogram")
plt.xlabel("GC Percentage")
plt.ylabel("Frequency")

# Zoom to 20–80%
plt.xlim(20, 80)

plt.grid(axis="y", alpha=0.75)
plt.tight_layout()
plt.show()


# ============================================================
# FIGURE 2: COMBINED PROTEIN-CODING + NON-CODING DENSITY PLOT
# ============================================================

# Select needed columns
cleaned_df2 = g_data[
    [
        "group",
        "protein_coding_gene_count",
        "non_coding_gene_count"
    ]
].copy()

# Convert gene counts to numeric
cleaned_df2[
    [
        "protein_coding_gene_count",
        "non_coding_gene_count"
    ]
] = cleaned_df2[
    [
        "protein_coding_gene_count",
        "non_coding_gene_count"
    ]
].apply(pd.to_numeric, errors="coerce")

# Remove missing values
cleaned_df2 = cleaned_df2.dropna()

# Calculate total number of genes
total_genes = (
    cleaned_df2["protein_coding_gene_count"] +
    cleaned_df2["non_coding_gene_count"]
)

# Remove genomes with zero total genes
cleaned_df2 = cleaned_df2[total_genes > 0].copy()

# Recalculate total genes after filtering
total_genes = (
    cleaned_df2["protein_coding_gene_count"] +
    cleaned_df2["non_coding_gene_count"]
)

# Calculate coding and non-coding proportions
cleaned_df2["coding_proportion"] = (
    cleaned_df2["protein_coding_gene_count"] /
    total_genes
)

cleaned_df2["non_coding_proportion"] = (
    cleaned_df2["non_coding_gene_count"] /
    total_genes
)


# Create combined figure
plt.figure(figsize=(12, 7))

x_vals = np.linspace(0, 1, 1000)

for group in sorted(cleaned_df2["group"].unique()):

    coding_data = cleaned_df2.loc[
        cleaned_df2["group"] == group,
        "coding_proportion"
    ].dropna()

    noncoding_data = cleaned_df2.loc[
        cleaned_df2["group"] == group,
        "non_coding_proportion"
    ].dropna()

    # Protein-coding genes = solid lines
    if len(coding_data) > 1 and coding_data.nunique() > 1:

        coding_density = gaussian_kde(coding_data)

        plt.plot(
            x_vals,
            coding_density(x_vals),
            lw=2,
            label=f"{group} - Protein-coding"
        )

    # Non-coding genes = dashed lines
    if len(noncoding_data) > 1 and noncoding_data.nunique() > 1:

        noncoding_density = gaussian_kde(noncoding_data)

        plt.plot(
            x_vals,
            noncoding_density(x_vals),
            lw=2,
            linestyle="--",
            label=f"{group} - Non-coding"
        )


plt.title(
    "Distribution of Protein-Coding and Non-Coding Gene Proportions by Group"
)

plt.xlabel("Gene Proportion")
plt.ylabel("Density")

plt.xlim(0, 1)

plt.legend(
    title="Group and Gene Type",
    bbox_to_anchor=(1.05, 1),
    loc="upper left"
)

plt.tight_layout()
plt.show()